### ISSUE TITLE
Add Tables.jl interface for fetching data

### ISSUE THREAD

**Issue by lungben** [felipenoris/Oracle.jl#20]
https://github.com/JuliaData/Tables.jl provides a uniform interface for tabular data, used e.g. for DataFrames and for data bases (e.g. LibPQ.jl).
It would make fetching results from Oracle data bases much easier if the Tables.jl interface would be supported.

**Comment by felipenoris** [comment]
See 8b35604da0c14d366bde349cb6164ce54ec5dbc5.
