### ISSUE TITLE
Crashing When Closing a Connection

### ISSUE THREAD

**Issue by BrettRToomey** [felipenoris/Oracle.jl#22]
Hello,

I have been experiencing a crash in my scripts while using the Oracle.jl package. I managed to minimise the code and generate this recreation:

```
julia> include("db.jl");

julia> c = Oracle.Connection(db_user, db_pass, db)
Oracle.Connection(Oracle.Context(Ptr{Nothing} @0x00007ffc4044c250), Ptr{Nothing} @0x00007ffc407053e0, Oracle.EncodingInfo("UTF-8", 4, "UTF-8", 4), nothing)

julia> Oracle.close(c)

julia> c = Oracle.Connection(db_user, db_pass, db)
Oracle.Connection(Oracle.Context(Ptr{Nothing} @0x00007ffc407096f0), Ptr{Nothing} @0x00007ffc40707320, Oracle.EncodingInfo("UTF-8", 4, "UTF-8", 4), nothing)

julia> Oracle.close(c)
zsh: segmentation fault  julia
```

`db.jl` only has db credentials and the db string, that way I don't risk leaking them.

I am on macOS Big Sur with an Intel-based MacBook. I am using Julia 1.6.1. Please ask if there is anything else you need from me!

**Comment by felipenoris** [comment]
@BrettRToomey can you downgrade to Oracle.jl v0.2.0 and repeat the test?

**Comment by BrettRToomey** [comment]
I tried that with the minimised sample and I can't seem to recreate the crash

**Comment by BrettRToomey** [comment]
And the original script doesn't crash either @felipenoris

**Comment by felipenoris** [comment]
I guess you're hitting https://github.com/oracle/odpi/issues/156 .
The quick fix is to create a single `Context` for your application and use [this](https://github.com/felipenoris/Oracle.jl/blob/ab15aed8e94788577dd86dd8dfbec001b684b5aa/src/connection.jl#L65) connection constructor.

A better solution is to use a [`Oracle.Pool`](https://felipenoris.github.io/Oracle.jl/stable/tutorial/#Session-Pools) and create connections from the pool. It can be made thread-safe if you use `create_mode=Oracle.ORA_MODE_CREATE_THREADED`.

**Comment by BrettRToomey** [comment]
I was planning to move to pools soon anyway, so it's nice to see that they get around this issue. Is there any way I can help? Although it seems like everything is done, we are just waiting on a new odpi release?

**Comment by felipenoris** [comment]
@BrettRToomey please, check if this is solved in the master branch.

**Comment by cjbj** [comment]
@felipenoris this is just a passing FYI. With ODPI-C 4.2 sessions pools are always created in threaded mode.  See https://oracle.github.io/odpi/doc/releasenotes.html#version-4-2-may-18-2021

**Comment by felipenoris** [comment]
@cjbj thanks for the info!

**Comment by BrettRToomey** [comment]
@felipenoris master branch has fixed the crash. Thanks!
